name: Проверка
on: [push]
jobs:
  linter:
    name: Линтер
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: flake8 .
  tests:
    name: Тесты
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pytest==6.2.5
    - name: Pytest
      run: pytest

